package Vista;
import java.awt.event.ActionListener;
import javax.swing.JButton;
import javax.swing.JOptionPane;
public class VistaPrincipal extends javax.swing.JFrame {
    public VistaPrincipal() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        CerrarSesión = new javax.swing.JButton();
        Batalla = new javax.swing.JButton();
        Torneo = new javax.swing.JButton();
        cantidadDeJugadores = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Menu Principal");

        CerrarSesión.setText("Cerrar sesión");
        CerrarSesión.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CerrarSesiónActionPerformed(evt);
            }
        });

        Batalla.setText("Batalla");
        Batalla.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BatallaActionPerformed(evt);
            }
        });

        Torneo.setText("Torneo");

        cantidadDeJugadores.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cantidadDeJugadoresActionPerformed(evt);
            }
        });

        jLabel2.setText("Ingrese Cantidad de Jugadores");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(Batalla)
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 180, Short.MAX_VALUE)
                                .addComponent(CerrarSesión)
                                .addContainerGap())
                            .addGroup(layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addComponent(cantidadDeJugadores, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jLabel2)
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(38, 38, 38)
                        .addComponent(Torneo)
                        .addContainerGap())))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(11, 11, 11)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(CerrarSesión))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Batalla)
                    .addComponent(cantidadDeJugadores, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addGap(18, 18, 18)
                .addComponent(Torneo)
                .addContainerGap(186, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void CerrarSesiónActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CerrarSesiónActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CerrarSesiónActionPerformed

    private void BatallaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BatallaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BatallaActionPerformed

    private void cantidadDeJugadoresActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cantidadDeJugadoresActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cantidadDeJugadoresActionPerformed

    /**
     * @param args the command line arguments
     */
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Batalla;
    private javax.swing.JButton CerrarSesión;
    private javax.swing.JButton Torneo;
    private javax.swing.JTextField cantidadDeJugadores;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    // End of variables declaration//GEN-END:variables
    public JButton getButtonCerrarSesion(){
        return this.CerrarSesión;
    }
    public JButton getButtonBatalla(){
        return this.Batalla;
    }
    public JButton getButtonTorneo(){
        return this.Torneo;
    }
    public int getCantidadDeJugadores(){
        return Integer.parseInt(this.cantidadDeJugadores.getText());
    }
    public String getTexto(){
        return this.cantidadDeJugadores.getText();
    }
    public void agregarListener(ActionListener al){
        this.CerrarSesión.addActionListener(al);
        this.Batalla.addActionListener(al);
        this.Torneo.addActionListener(al);
    }
}
